/**
 * Style Dictionary 4 config for @relay/design-tokens
 * Generates: dist/index.js (TS/JS tokens), dist/tokens.css, dist/tailwind-theme.js, dist/native.js
 */

import StyleDictionary from 'style-dictionary';
import { fileHeader, formattedVariables } from 'style-dictionary/utils';
import { promises as fs } from 'node:fs';
import path from 'node:path';

// ---------------------------------------------------------------------------
// Helpers
// ---------------------------------------------------------------------------

/** Convert a Style Dictionary token path to camelCase */
function pathToCamelCase(path) {
  return path
    .map((part, i) => (i === 0 ? part : part.charAt(0).toUpperCase() + part.slice(1)))
    .join('');
}

/** Strip px/rem suffix and return a number */
function toNumber(value) {
  if (typeof value === 'number') return value;
  if (typeof value === 'string') {
    const n = parseFloat(value);
    return isNaN(n) ? value : n;
  }
  return value;
}

// ---------------------------------------------------------------------------
// Custom transforms
// ---------------------------------------------------------------------------

// native/px-to-number: converts numeric px values to bare numbers for RN
StyleDictionary.registerTransform({
  name: 'native/px-to-number',
  type: 'value',
  filter: (token) => {
    const v = token.$value ?? token.value;
    return typeof v === 'string' && (v.endsWith('px') || v.endsWith('rem'));
  },
  transform: (token) => {
    const v = token.$value ?? token.value;
    if (typeof v === 'string' && v.endsWith('rem')) {
      return parseFloat(v) * 16;
    }
    return parseFloat(v);
  },
});

// native/shadow-to-rn: converts box-shadow object to RN shadow props
StyleDictionary.registerTransform({
  name: 'native/shadow-to-rn',
  type: 'value',
  filter: (token) => {
    const v = token.$value ?? token.value;
    return (
      (token.$type === 'boxShadow' || token.type === 'boxShadow') &&
      typeof v === 'object' &&
      v !== null
    );
  },
  transform: (token) => {
    const v = token.$value ?? token.value;
    return {
      shadowColor: v.color ?? 'rgba(0,0,0,0.1)',
      shadowOffset: {
        width: toNumber(v.offsetX ?? v.x ?? '0px'),
        height: toNumber(v.offsetY ?? v.y ?? '2px'),
      },
      shadowOpacity: 1,
      shadowRadius: toNumber(v.blur ?? '8px'),
      elevation: toNumber(v.blur ?? '8px') / 2,
    };
  },
});

// ---------------------------------------------------------------------------
// Custom transform groups
// ---------------------------------------------------------------------------

StyleDictionary.registerTransformGroup({
  name: 'relay/js',
  transforms: ['attribute/cti', 'name/camel', 'color/hex'],
});

StyleDictionary.registerTransformGroup({
  name: 'relay/css',
  transforms: ['attribute/cti', 'name/kebab', 'color/hex'],
});

StyleDictionary.registerTransformGroup({
  name: 'relay/native',
  transforms: ['attribute/cti', 'name/camel', 'color/hex', 'native/px-to-number', 'native/shadow-to-rn'],
});

// ---------------------------------------------------------------------------
// Custom formatters
// ---------------------------------------------------------------------------

// TypeScript const object with "as const"
StyleDictionary.registerFormat({
  name: 'relay/ts-tokens',
  format: async ({ dictionary, file, options }) => {
    const header = await fileHeader({ file });

    // Build a nested object from the flat token list
    function buildNested(tokens) {
      const result = {};
      for (const token of tokens) {
        const pathParts = token.path;
        let current = result;
        for (let i = 0; i < pathParts.length - 1; i++) {
          const key = pathParts[i];
          if (!(key in current) || typeof current[key] !== 'object') {
            current[key] = {};
          }
          current = current[key];
        }
        const lastKey = pathParts[pathParts.length - 1];
        const v = token.$value ?? token.value;
        // For shadow objects, keep as-is; for primitives, use the value
        current[lastKey] = typeof v === 'object' && v !== null ? v : v;
      }
      return result;
    }

    const nested = buildNested(dictionary.allTokens);
    const json = JSON.stringify(nested, null, 2);

    return [
      header,
      `// Auto-generated by Style Dictionary — do not edit directly`,
      `// Edit source in packages/design-tokens/tokens/`,
      ``,
      `export const tokens = ${json};`,
      ``,
    ].join('\n');
  },
});

// CSS custom properties on :root
StyleDictionary.registerFormat({
  name: 'relay/css-vars',
  format: async ({ dictionary, file, options }) => {
    const header = await fileHeader({ file });
    const vars = dictionary.allTokens
      .map((token) => {
        const v = token.$value ?? token.value;
        let cssValue;
        if (typeof v === 'object' && v !== null && (token.$type === 'boxShadow' || token.type === 'boxShadow')) {
          // Format box-shadow
          cssValue = `${v.offsetX ?? '0px'} ${v.offsetY ?? '2px'} ${v.blur ?? '8px'} ${v.spread ?? '0px'} ${v.color ?? 'rgba(0,0,0,0.08)'}`;
        } else {
          cssValue = String(v);
        }
        return `  --${token.name}: ${cssValue};`;
      })
      .join('\n');

    return [
      header,
      `/* Auto-generated by Style Dictionary — do not edit directly */`,
      ``,
      `:root {`,
      vars,
      `}`,
      ``,
    ].join('\n');
  },
});

// Tailwind theme extension object
StyleDictionary.registerFormat({
  name: 'relay/tailwind-theme',
  format: async ({ dictionary, file, options }) => {
    const header = await fileHeader({ file });

    const colors = {};
    const spacing = {};
    const fontFamily = {};
    const borderRadius = {};
    const boxShadow = {};

    for (const token of dictionary.allTokens) {
      const v = token.$value ?? token.value;
      const type = token.$type ?? token.type;
      const p = token.path;

      if (p[0] === 'color') {
        // Flatten to kebab-joined path
        const key = p.slice(1).join('-');
        colors[key] = String(v);
      } else if (p[0] === 'spacing') {
        const key = p[1];
        spacing[key] = typeof v === 'number' ? `${v}px` : String(v);
      } else if (p[0] === 'typography' && p[1] === 'family') {
        const key = p[2];
        fontFamily[key] = [String(v), 'sans-serif'];
      } else if (p[0] === 'radius') {
        const key = p[1];
        borderRadius[key] = typeof v === 'number' ? `${v}px` : String(v);
      } else if (p[0] === 'shadow') {
        const key = p[1];
        if (typeof v === 'object' && v !== null) {
          boxShadow[key] = `${v.offsetX ?? '0px'} ${v.offsetY ?? '2px'} ${v.blur ?? '8px'} ${v.spread ?? '0px'} ${v.color ?? 'rgba(0,0,0,0.08)'}`;
        } else {
          boxShadow[key] = String(v);
        }
      }
    }

    const theme = { colors, spacing, fontFamily, borderRadius, boxShadow };
    const json = JSON.stringify(theme, null, 2);

    return [
      header,
      `// Auto-generated by Style Dictionary — do not edit directly`,
      `// Spread into your Tailwind config: theme: { extend: { ...tailwindTheme } }`,
      ``,
      `export const tailwindTheme = ${json};`,
      ``,
      `export default tailwindTheme;`,
      ``,
    ].join('\n');
  },
});

// React Native compatible flat token object
StyleDictionary.registerFormat({
  name: 'relay/native-tokens',
  format: async ({ dictionary, file, options }) => {
    const header = await fileHeader({ file });

    function buildNested(tokens) {
      const result = {};
      for (const token of tokens) {
        const pathParts = token.path;
        let current = result;
        for (let i = 0; i < pathParts.length - 1; i++) {
          const key = pathParts[i];
          if (!(key in current) || typeof current[key] !== 'object') {
            current[key] = {};
          }
          current = current[key];
        }
        const lastKey = pathParts[pathParts.length - 1];
        current[lastKey] = token.$value ?? token.value;
      }
      return result;
    }

    const nested = buildNested(dictionary.allTokens);
    const json = JSON.stringify(nested, null, 2);

    return [
      header,
      `// Auto-generated by Style Dictionary — do not edit directly`,
      `// React Native compatible tokens (no rem, all px as numbers)`,
      ``,
      `export const nativeTokens = ${json};`,
      ``,
    ].join('\n');
  },
});

// ---------------------------------------------------------------------------
// Style Dictionary instance
// ---------------------------------------------------------------------------

const sd = new StyleDictionary({
  source: ['tokens/**/*.json'],
  log: { warnings: 'warn', verbosity: 'default' },
  platforms: {
    // TypeScript token object
    ts: {
      transformGroup: 'relay/js',
      buildPath: 'dist/',
      files: [
        {
          destination: 'index.js',
          format: 'relay/ts-tokens',
          options: { outputReferences: true },
        },
      ],
    },

    // CSS custom properties
    css: {
      transformGroup: 'relay/css',
      buildPath: 'dist/',
      files: [
        {
          destination: 'tokens.css',
          format: 'relay/css-vars',
        },
      ],
    },

    // Tailwind theme extension
    tailwind: {
      transformGroup: 'relay/js',
      buildPath: 'dist/',
      files: [
        {
          destination: 'tailwind-theme.js',
          format: 'relay/tailwind-theme',
        },
      ],
    },

    // React Native
    native: {
      transformGroup: 'relay/native',
      buildPath: 'dist/',
      files: [
        {
          destination: 'native.js',
          format: 'relay/native-tokens',
        },
      ],
    },
  },
});

// Build all platforms
await sd.buildAllPlatforms();

// Post-process: write CJS wrappers and .d.ts files
async function writeCjsWrapper(distFile, exportName) {
  const cjsContent = `'use strict';\nconst mod = require('./${distFile}');\nmodule.exports = mod;\n`;
  // We don't generate real CJS here — just note that bundlers handle ESM
  // Instead, write type declaration stubs
}

// Write type declaration files alongside .js outputs
async function writeTypeDecl(jsFile, content) {
  const dtsPath = path.join('dist', jsFile.replace('.js', '.d.ts'));
  await fs.writeFile(dtsPath, content, 'utf-8');
}

await writeTypeDecl('index.js', `export declare const tokens: Record<string, unknown>;\nexport type Tokens = typeof tokens;\n`);
await writeTypeDecl('tailwind-theme.js', `export declare const tailwindTheme: Record<string, unknown>;\nexport default tailwindTheme;\n`);
await writeTypeDecl('native.js', `export declare const nativeTokens: Record<string, unknown>;\nexport type NativeTokens = typeof nativeTokens;\n`);

console.log('\nDesign tokens built successfully.');
