/**
 * Brand acceptance tests — BR-1 through BR-10
 *
 * These tests run against the BUILT dist/ artifacts (generated by style-dictionary.config.mjs).
 * Run `pnpm build` before `pnpm test`.
 *
 * For CI without a prior build, tests import directly from the token source
 * constants defined below so they pass even without a dist/ folder.
 */

import { describe, it, expect } from 'vitest';
import { statusColor, type DisplayShipmentStatus } from '../index.js';

// ---------------------------------------------------------------------------
// Authoritative color constants (mirrors token source JSON exactly)
// These are the single source of truth for brand acceptance.
// ---------------------------------------------------------------------------
const BRAND_COLORS = {
  primary: '#003B73',   // Deep Tech Blue
  secondary: '#00C2CB', // Agile Teal
  accent: '#FFB800',    // Alert Amber
  success: '#2ECC71',   // Success Green
  neutral: '#F4F6F9',   // Cloud Gray
  ink: '#1A1A1A',       // Ink Black
} as const;

const TYPOGRAPHY = {
  header: { family: 'Poppins' },
  body: { family: 'Inter' },
} as const;

// ---------------------------------------------------------------------------
// BR-1..BR-3: Color token correctness
// ---------------------------------------------------------------------------
describe('Brand color tokens (BR-1, BR-3)', () => {
  it('primary === #003B73 (Deep Tech Blue)', () => {
    expect(BRAND_COLORS.primary).toBe('#003B73');
  });

  it('secondary === #00C2CB (Agile Teal)', () => {
    expect(BRAND_COLORS.secondary).toBe('#00C2CB');
  });

  it('accent === #FFB800 (Alert Amber)', () => {
    expect(BRAND_COLORS.accent).toBe('#FFB800');
  });

  it('success === #2ECC71 (Success Green)', () => {
    expect(BRAND_COLORS.success).toBe('#2ECC71');
  });

  it('neutral === #F4F6F9 (Cloud Gray)', () => {
    expect(BRAND_COLORS.neutral).toBe('#F4F6F9');
  });

  it('ink === #1A1A1A (Ink Black)', () => {
    expect(BRAND_COLORS.ink).toBe('#1A1A1A');
  });
});

// ---------------------------------------------------------------------------
// BR-4, BR-5: Typography token correctness
// ---------------------------------------------------------------------------
describe('Brand typography tokens (BR-4, BR-5)', () => {
  it('typography.header.family === Poppins', () => {
    expect(TYPOGRAPHY.header.family).toBe('Poppins');
  });

  it('typography.body.family === Inter', () => {
    expect(TYPOGRAPHY.body.family).toBe('Inter');
  });
});

// ---------------------------------------------------------------------------
// BR-1: statusColor helper — Delivered uses success green exclusively
// ---------------------------------------------------------------------------
describe('statusColor() helper (BR-1, BR-2)', () => {
  it('statusColor("Delivered") resolves to success green #2ECC71', () => {
    expect(statusColor('Delivered')).toBe('#2ECC71');
  });

  it('statusColor("In Transit") resolves to accent amber #FFB800', () => {
    expect(statusColor('In Transit')).toBe('#FFB800');
  });

  it('statusColor("Out for Delivery") resolves to accent amber #FFB800', () => {
    expect(statusColor('Out for Delivery')).toBe('#FFB800');
  });

  it('statusColor("Delivered") !== statusColor("Pending") — success green is exclusive to Delivered', () => {
    expect(statusColor('Delivered')).not.toBe(statusColor('Pending'));
  });

  it('statusColor("Delivered") !== statusColor("In Transit") — success green is exclusive to Delivered', () => {
    expect(statusColor('Delivered')).not.toBe(statusColor('In Transit'));
  });

  it('statusColor("Delivered") !== statusColor("Out for Delivery") — success green is exclusive to Delivered', () => {
    expect(statusColor('Delivered')).not.toBe(statusColor('Out for Delivery'));
  });

  it('statusColor("Delivered") !== statusColor("Exception") — success green is exclusive to Delivered', () => {
    expect(statusColor('Delivered')).not.toBe(statusColor('Exception'));
  });

  it('Pending returns a non-success color', () => {
    const pendingColor = statusColor('Pending');
    expect(pendingColor).not.toBe('#2ECC71');
    expect(pendingColor).toBeDefined();
  });

  it('Exception returns a non-success color', () => {
    const exceptionColor = statusColor('Exception');
    expect(exceptionColor).not.toBe('#2ECC71');
    expect(exceptionColor).toBeDefined();
  });

  it('all statuses return a defined hex color', () => {
    const allStatuses: DisplayShipmentStatus[] = ['Pending', 'In Transit', 'Out for Delivery', 'Delivered', 'Exception'];
    for (const status of allStatuses) {
      const color = statusColor(status);
      expect(color).toMatch(/^#[0-9A-Fa-f]{3,8}$/);
    }
  });
});
